# Generated by Django 5.2.14 on 2026-05-23 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PoojaService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('estimated_duration_hours', models.DecimalField(decimal_places=1, max_digits=3)),
                ('base_price', models.IntegerField()),
                ('samagri_included', models.BooleanField(default=True)),
                ('image', models.URLField(blank=True, help_text='URL to service image', max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Pooja Service',
                'verbose_name_plural': 'Pooja Services',
            },
        ),
        migrations.CreateModel(
            name='Pandit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('profile_picture', models.URLField(blank=True, help_text='URL to profile picture', max_length=500, null=True)),
                ('languages_spoken', models.CharField(help_text='e.g. Hindi, Sanskrit, Marathi', max_length=255)),
                ('base_city', models.CharField(max_length=100)),
                ('is_available', models.BooleanField(default=True, help_text='Global operational status tracker')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pandit_profile', to=settings.AUTH_USER_MODEL)),
                ('specialization', models.ManyToManyField(related_name='pandits', to='bookings.poojaservice')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_pooja', models.DateField()),
                ('muhurat_time', models.TimeField()),
                ('venue_address', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Assignment'), ('CONFIRMED', 'Pandit Assigned'), ('COMPLETED', 'Pooja Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_bookings', to=settings.AUTH_USER_MODEL)),
                ('assigned_pandit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.pandit')),
                ('pooja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.poojaservice')),
            ],
            options={
                'ordering': ['date_of_pooja', 'muhurat_time'],
            },
        ),
    ]
