# Generated by Django 5.2.14 on 2026-05-26 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poojaservice',
            name='samagri_included',
        ),
    ]
